### ISSUE TITLE
Develop HPA machine learning algorithm and rules

### ISSUE THREAD

**Issue by pzou1974** [intuit/foremast#103]
1)Define rule
2)design algorithm focus on metric correlation.  (Bayes' Rule)

**Comment by dwding18** [comment]
The rule will be in configuration and used to generalize the logic in Brain HPA logic. 
In this phase, the rules will be shared and default.

**Comment by pzou1974** [comment]
Add one more sprint because model generation need to be smart enough to detect seasonality vs non seasonality,

**Comment by pzou1974** [comment]
mark as duplicated as #123
