### ISSUE TITLE
Demo run unable to see foremast-ai-api & foremast-engine

### ISSUE THREAD

**Issue by asthinasthi** [intuit/foremast#138]
I am following this guide: https://github.com/intuit/foremast/blob/release-0.5/docs/guides/installation.md
After running `kubectl create -Rf deploy/foremast/`
I see these pods
```
NAME                                  READY   STATUS              RESTARTS   AGE
elasticsearch-0                       0/1     Init:1/3            0          1m
foremast-barrelman-58d65495bc-v5j96   1/1     Running             0          1m
foremast-brain-75899f6858-5dmcn       0/1     ContainerCreating   0          1m
foremast-service-8cff5d667-vfb5j      0/1     ContainerCreating   0          1m
```

I don't see `foremast-ai-api` & `foremast-engine` as per the docs. Have they been renamed?

**Comment by shaoxt** [comment]
Thanks for figuring this out.  Have already updated the doc.
