### ISSUE TITLE
Improve Marketing Website

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/foremast#14]
I did an audit of the marketing website and found the following: 

1. the `features` under `Everything about Foremast` should be center aligned. Currently its a little off balance
2. the footer is left justified. would look a lot better in the center
3. on mobile the image overflows
4. the footer is not sticky. on larger screens this means the footer will be at the end of the content rather than the bottom of the page
5. on getting started the highlighted header on the right skips `Installing Foremast`
6. on getting started you link to github.intuit.com
7. on about and about screens floating footer is present on normal screens
8. on about page it says i can contact you on slack but doesn't link to the slack team
9. same thing for the calender. what are the meetup days?

**Comment by srivathsanvc** [comment]
Thanks for the detailed review. Much appreciate it.. Few q's:

- `on getting started you link to github.intuit.com`: The links seem to properly link to "github.com/intuit/foremast" - can you elaborate on the location where you see the incorrect link?

- `on about and about screens floating footer is present on normal screens`: not sure what you are referring to here?

**Comment by hipstersmoothie** [comment]
> on getting started you link to github.intuit.com

Hmm most of the links on the getting started page were pointing to `github.intuit.com` thismorning but it seems to be fixed now. Maybe I had a cached version somehow.

> on about and about screens floating footer is present on normal screens

The footer is not at the foot of the page when the content is short.

<img width="1678" alt="screen shot 2019-01-03 at 3 20 16 pm" src="https://user-images.githubusercontent.com/1192452/50666777-1e8d3a00-0f6b-11e9-9b10-ac6d77adb0ae.png">

Should be easy to fix with flexbox https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

**Comment by hipstersmoothie** [comment]
Upon further review I have some comments about the navbar as well:

1. The word foremast is not aligned with the rest of the text
2. Personally I think it would look better if the links (getting started, about, contact) were right justified

**Comment by davemasselink** [comment]
@srivathsanvc, I completed the remaining changes which we discussed earlier this week via this PR, though I'm not able to assign reviewers or assignee there - https://github.com/intuit/foremast/pull/20
