### ISSUE TITLE
Change or add slack link to request invite on README

### ISSUE THREAD

**Issue by rljohnsn** [intuit/foremast#65]
😄  Or send me an invite lance.johnson@8x8.com

**Comment by pzou1974** [comment]
Thank you, Lance!  I invited you

**Comment by pzou1974** [comment]
Srivathsan,  
Can you allow everybody to joins slack by default?
https://get.slack.help/hc/en-us/articles/115004854783

**Comment by srivathsanvc** [comment]
Slack is open for email addresses in the company domains where we have participation from. 

Lance - anyone at 8x8 should be able to use Foremast slack..
